{
  "language": "java",
  "jdk": "oraclejdk8",
  "sudo": false,
  "cache": {
    "directories": [
      "$HOME/.m2/repository",
      "$HOME/apache-maven-3.5.0",
      ""
    ]
  },
  "addons": {
    "apt": {
      "packages": [
        "graphviz",
        "oracle-java8-installer"
      ]
    },
  },
  "before_install": [
    "export JAVA_8_HOME=/usr/lib/jvm/java-8-oracle",
    "export M2_HOME=$HOME/apache-maven-3.5.0",
    "if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz | tar zxf - -C $HOME; fi",
    "export PATH=$M2_HOME/bin:$PATH",
    "wget https://raw.githubusercontent.com/earcam/io.earcam.maven/master/io.earcam.maven.toolchain/src/main/resources/toolchain/continuous-integration-hotspot-linux-debian-amd64.xml -O  ~/.m2/toolchains.xml",
    
  ],
  "install": [
    "chmod go-rwx -R $HOME/.m2"
  ],
  "script": [
    "travis_wait 30 mvn -P '!strict' -DskipTests clean verify"
  ],
}
